### ISSUE TITLE
Introduction: Fusion of Text and Vision

### ISSUE THREAD

**Issue by snehilsanyal** [SuryaKrishna02/computer-vision-course#2]
Hey team members, this is the issue for the Introduction section of the chapter Fusion of Text and Vision. 
**Main issue:** https://github.com/johko/computer-vision-course/issues/54 

### Sub-tasks:

- [x] What is multimodality? Notion of multimodality.
- [x] Real life examples of multimodality.
- [x] Include cool infographics and tips.
- [x] Brief on Multimodal Data, Tasks and Models
- [x] Example of multimodal search and other cool applications (mostly topics that are covered later)
- [x] Image links change after merge
- [x] Final structuring
- [x] PR
- [x] Reviews and Edits
- [x] Push to Main

**Comment by snehilsanyal** [comment]
Completed all tasks, and pushed to the main fork.
Closing the issue....
**Merged here:** https://github.com/johko/computer-vision-course/pull/126
