### ISSUE TITLE
MultiModal Tasks and Models Part - 1

### ISSUE THREAD

**Issue by SuryaKrishna02** [SuryaKrishna02/computer-vision-course#4]
Hey team members, this is the issue for the First part of the Multimodal Tasks and Models 
**Main issue:** https://github.com/johko/computer-vision-course/issues/54 

### Sub-tasks:

- [x] Overview of Different Tasks and Models
- [x] Examples of Tasks and their Corresponding Model Names.
- [x] Document Visual Question Answering (text + vision), Models: LayoutLM, Nougat, Donut.
- [x] Image to Text, Visual Question Answering Models
- [x] Text to Image (synthesis and generation) SD, IF etc
- [x] Final structuring
- [x] PR
- [x] Reviews and Edits
- [x] Push to Main

**Comment by snehilsanyal** [comment]
Completed here: https://github.com/johko/computer-vision-course/pull/151 
Closing the issue.
Thank you @SuryaKrishna02 🤗
