### ISSUE TITLE
Introduction to Vision Language Models

### ISSUE THREAD

**Issue by charchit7** [SuryaKrishna02/computer-vision-course#5]
Hey Minna(everyone in Japanese, lol),

This is the issue for VLM introduction basics.
Main Issue : https://github.com/johko/computer-vision-course/issues/54

## Subtask: 

- [x] Overview  
- [x] Brief on Multi-modal (as discussed before)
- [x] Mechanism
- [x] Intro to Next section.
- [x] PR
- [x] Reviews and Edit
- [x] Push to Main!

**Comment by snehilsanyal** [comment]
Completed here: https://github.com/johko/computer-vision-course/pull/147
Closing the issue.
Thank you @charchit7 🤗
