### ISSUE TITLE
Add supplementary resources

### ISSUE THREAD

**Issue by snehilsanyal** [SuryaKrishna02/computer-vision-course#8]
Hey everyone 🤗 
Adding supplementary resources section for our Unit. Inspired by: [HF Audio Course](https://huggingface.co/learn/audio-course/chapter5/supplemental_reading)
**Issue:** #54

**Tasks:**
- [x] Add 6-7 resources for multimodal models, containing papers, courses, any other newsletters,
- [x] Check on with other chapters in the same unit.
- [x] PR to main.

**Comment by snehilsanyal** [comment]
Complete here: https://github.com/johko/computer-vision-course/pull/173
Closing the issue,
